### PR TITLE
Adds "venue_name" value to FetLifeEvent.

### PR DESCRIPTION
**Pull request by corsair**
This fixes the missing venue_name value within FetlifeEvent.

### CODE REVIEW

**Comment by meitar** [comment]
If a venue name is optional this needs to be guarded by an `if` or it will cause an exception when an event does not have a venue name.

**Comment by corsair** [comment]
Thanks for catching that. The same actually applies to many of the other values not set to required, so I've guarded those as well. Fix applied.

**Comment by meitar** [comment]
> The same actually applies to many of the other values not set to required

Yeah, this kind of check should really become a unit test but I lost interest in this library just when I was setting that up. See the `tests` directory for that.

**Comment by meitar** [comment]
@crr For future reference, the `if`s should be guarding the `item()` method, not the `nodeValue` property. Fixed in 92736cba44b765f086db8b80869312de6344b8cd.

**Pull request merged**
